// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: game.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameEngine_ValidateAndMakeMove_FullMethodName  = "/game.GameEngine/ValidateAndMakeMove"
	GameEngine_HandleLobbyAction_FullMethodName    = "/game.GameEngine/HandleLobbyAction"
	GameEngine_HandleGameAction_FullMethodName     = "/game.GameEngine/HandleGameAction"
	GameEngine_GetGameStateSnapshot_FullMethodName = "/game.GameEngine/GetGameStateSnapshot"
)

// GameEngineClient is the client API for GameEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameEngineClient interface {
	ValidateAndMakeMove(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*GameStateResponse, error)
	HandleLobbyAction(ctx context.Context, in *LobbyActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	HandleGameAction(ctx context.Context, in *GameActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	GetGameStateSnapshot(ctx context.Context, in *GameStateRequest, opts ...grpc.CallOption) (*ActionResponse, error)
}

type gameEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewGameEngineClient(cc grpc.ClientConnInterface) GameEngineClient {
	return &gameEngineClient{cc}
}

func (c *gameEngineClient) ValidateAndMakeMove(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*GameStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GameStateResponse)
	err := c.cc.Invoke(ctx, GameEngine_ValidateAndMakeMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameEngineClient) HandleLobbyAction(ctx context.Context, in *LobbyActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, GameEngine_HandleLobbyAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameEngineClient) HandleGameAction(ctx context.Context, in *GameActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, GameEngine_HandleGameAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameEngineClient) GetGameStateSnapshot(ctx context.Context, in *GameStateRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, GameEngine_GetGameStateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameEngineServer is the server API for GameEngine service.
// All implementations must embed UnimplementedGameEngineServer
// for forward compatibility.
type GameEngineServer interface {
	ValidateAndMakeMove(context.Context, *MoveRequest) (*GameStateResponse, error)
	HandleLobbyAction(context.Context, *LobbyActionRequest) (*ActionResponse, error)
	HandleGameAction(context.Context, *GameActionRequest) (*ActionResponse, error)
	GetGameStateSnapshot(context.Context, *GameStateRequest) (*ActionResponse, error)
	mustEmbedUnimplementedGameEngineServer()
}

// UnimplementedGameEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameEngineServer struct{}

func (UnimplementedGameEngineServer) ValidateAndMakeMove(context.Context, *MoveRequest) (*GameStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAndMakeMove not implemented")
}
func (UnimplementedGameEngineServer) HandleLobbyAction(context.Context, *LobbyActionRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleLobbyAction not implemented")
}
func (UnimplementedGameEngineServer) HandleGameAction(context.Context, *GameActionRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleGameAction not implemented")
}
func (UnimplementedGameEngineServer) GetGameStateSnapshot(context.Context, *GameStateRequest) (*ActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGameStateSnapshot not implemented")
}
func (UnimplementedGameEngineServer) mustEmbedUnimplementedGameEngineServer() {}
func (UnimplementedGameEngineServer) testEmbeddedByValue()                    {}

// UnsafeGameEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameEngineServer will
// result in compilation errors.
type UnsafeGameEngineServer interface {
	mustEmbedUnimplementedGameEngineServer()
}

func RegisterGameEngineServer(s grpc.ServiceRegistrar, srv GameEngineServer) {
	// If the following call panics, it indicates UnimplementedGameEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameEngine_ServiceDesc, srv)
}

func _GameEngine_ValidateAndMakeMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameEngineServer).ValidateAndMakeMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameEngine_ValidateAndMakeMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameEngineServer).ValidateAndMakeMove(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameEngine_HandleLobbyAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LobbyActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameEngineServer).HandleLobbyAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameEngine_HandleLobbyAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameEngineServer).HandleLobbyAction(ctx, req.(*LobbyActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameEngine_HandleGameAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameEngineServer).HandleGameAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameEngine_HandleGameAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameEngineServer).HandleGameAction(ctx, req.(*GameActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameEngine_GetGameStateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameEngineServer).GetGameStateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameEngine_GetGameStateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameEngineServer).GetGameStateSnapshot(ctx, req.(*GameStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameEngine_ServiceDesc is the grpc.ServiceDesc for GameEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.GameEngine",
	HandlerType: (*GameEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateAndMakeMove",
			Handler:    _GameEngine_ValidateAndMakeMove_Handler,
		},
		{
			MethodName: "HandleLobbyAction",
			Handler:    _GameEngine_HandleLobbyAction_Handler,
		},
		{
			MethodName: "HandleGameAction",
			Handler:    _GameEngine_HandleGameAction_Handler,
		},
		{
			MethodName: "GetGameStateSnapshot",
			Handler:    _GameEngine_GetGameStateSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game.proto",
}
