// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	PieceId       string                 `protobuf:"bytes,3,opt,name=piece_id,json=pieceId,proto3" json:"piece_id,omitempty"`
	OriginX       int32                  `protobuf:"varint,4,opt,name=origin_x,json=originX,proto3" json:"origin_x,omitempty"`
	OriginY       int32                  `protobuf:"varint,5,opt,name=origin_y,json=originY,proto3" json:"origin_y,omitempty"`
	Rotation      int32                  `protobuf:"varint,6,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Flip          bool                   `protobuf:"varint,7,opt,name=flip,proto3" json:"flip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *MoveRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MoveRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *MoveRequest) GetPieceId() string {
	if x != nil {
		return x.PieceId
	}
	return ""
}

func (x *MoveRequest) GetOriginX() int32 {
	if x != nil {
		return x.OriginX
	}
	return 0
}

func (x *MoveRequest) GetOriginY() int32 {
	if x != nil {
		return x.OriginY
	}
	return 0
}

func (x *MoveRequest) GetRotation() int32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *MoveRequest) GetFlip() bool {
	if x != nil {
		return x.Flip
	}
	return false
}

type GameStateResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsValid           bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CurrentTurnUserId int32                  `protobuf:"varint,3,opt,name=current_turn_user_id,json=currentTurnUserId,proto3" json:"current_turn_user_id,omitempty"`
	State             string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GameStateResponse) Reset() {
	*x = GameStateResponse{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateResponse) ProtoMessage() {}

func (x *GameStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateResponse.ProtoReflect.Descriptor instead.
func (*GameStateResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *GameStateResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *GameStateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GameStateResponse) GetCurrentTurnUserId() int32 {
	if x != nil {
		return x.CurrentTurnUserId
	}
	return 0
}

func (x *GameStateResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type LobbyActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LobbyActionRequest) Reset() {
	*x = LobbyActionRequest{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LobbyActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LobbyActionRequest) ProtoMessage() {}

func (x *LobbyActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LobbyActionRequest.ProtoReflect.Descriptor instead.
func (*LobbyActionRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *LobbyActionRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LobbyActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *LobbyActionRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type GameActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameActionRequest) Reset() {
	*x = GameActionRequest{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameActionRequest) ProtoMessage() {}

func (x *GameActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameActionRequest.ProtoReflect.Descriptor instead.
func (*GameActionRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *GameActionRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GameActionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *GameActionRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type GameStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateRequest) Reset() {
	*x = GameStateRequest{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateRequest) ProtoMessage() {}

func (x *GameStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateRequest.ProtoReflect.Descriptor instead.
func (*GameStateRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *GameStateRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ActionResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\"\xbd\x01\n" +
	"\vMoveRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\x12\x19\n" +
	"\bpiece_id\x18\x03 \x01(\tR\apieceId\x12\x19\n" +
	"\borigin_x\x18\x04 \x01(\x05R\aoriginX\x12\x19\n" +
	"\borigin_y\x18\x05 \x01(\x05R\aoriginY\x12\x1a\n" +
	"\brotation\x18\x06 \x01(\x05R\brotation\x12\x12\n" +
	"\x04flip\x18\a \x01(\bR\x04flip\"\x9a\x01\n" +
	"\x11GameStateResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12/\n" +
	"\x14current_turn_user_id\x18\x03 \x01(\x05R\x11currentTurnUserId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"_\n" +
	"\x12LobbyActionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"^\n" +
	"\x11GameActionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"+\n" +
	"\x10GameStateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"y\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state2\x9d\x02\n" +
	"\n" +
	"GameEngine\x12A\n" +
	"\x13ValidateAndMakeMove\x12\x11.game.MoveRequest\x1a\x17.game.GameStateResponse\x12C\n" +
	"\x11HandleLobbyAction\x12\x18.game.LobbyActionRequest\x1a\x14.game.ActionResponse\x12A\n" +
	"\x10HandleGameAction\x12\x17.game.GameActionRequest\x1a\x14.game.ActionResponse\x12D\n" +
	"\x14GetGameStateSnapshot\x12\x16.game.GameStateRequest\x1a\x14.game.ActionResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_game_proto_goTypes = []any{
	(*MoveRequest)(nil),        // 0: game.MoveRequest
	(*GameStateResponse)(nil),  // 1: game.GameStateResponse
	(*LobbyActionRequest)(nil), // 2: game.LobbyActionRequest
	(*GameActionRequest)(nil),  // 3: game.GameActionRequest
	(*GameStateRequest)(nil),   // 4: game.GameStateRequest
	(*ActionResponse)(nil),     // 5: game.ActionResponse
}
var file_game_proto_depIdxs = []int32{
	0, // 0: game.GameEngine.ValidateAndMakeMove:input_type -> game.MoveRequest
	2, // 1: game.GameEngine.HandleLobbyAction:input_type -> game.LobbyActionRequest
	3, // 2: game.GameEngine.HandleGameAction:input_type -> game.GameActionRequest
	4, // 3: game.GameEngine.GetGameStateSnapshot:input_type -> game.GameStateRequest
	1, // 4: game.GameEngine.ValidateAndMakeMove:output_type -> game.GameStateResponse
	5, // 5: game.GameEngine.HandleLobbyAction:output_type -> game.ActionResponse
	5, // 6: game.GameEngine.HandleGameAction:output_type -> game.ActionResponse
	5, // 7: game.GameEngine.GetGameStateSnapshot:output_type -> game.ActionResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
