// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v7.36.0
// source: game.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "game";

export interface MoveRequest {
  userId: number;
  color: string;
  pieceId: string;
  originX: number;
  originY: number;
  rotation: number;
  flip: boolean;
}

export interface GameStateResponse {
  isValid: boolean;
  errorMessage: string;
  currentTurnUserId: number;
  state: string;
}

export interface GameActionRequest {
  userId: number;
  action: string;
  payload: string;
}

export interface GameStateRequest {
  userId: number;
}

export interface ActionResponse {
  success: boolean;
  errorCode: string;
  message: string;
  state: string;
}

export interface CreateLobbyPayload {
  userName: string;
  maxPlayers: number;
}

export interface JoinLobbyPayload {
  userName: string;
  lobbyId: string;
}

export interface LobbyIdOnlyPayload {
  lobbyId: string;
}

export interface EmptyPayload {
}

export interface LobbyActionRequest {
  userId: number;
  payload:
    | { $case: "createLobby"; createLobby: CreateLobbyPayload }
    | { $case: "joinLobby"; joinLobby: JoinLobbyPayload }
    | { $case: "toggleReady"; toggleReady: LobbyIdOnlyPayload }
    | { $case: "leaveLobby"; leaveLobby: EmptyPayload }
    | { $case: "beginReadyCheck"; beginReadyCheck: LobbyIdOnlyPayload }
    | { $case: "acceptReadyCheck"; acceptReadyCheck: LobbyIdOnlyPayload }
    | { $case: "declineReadyCheck"; declineReadyCheck: LobbyIdOnlyPayload }
    | undefined;
}

function createBaseMoveRequest(): MoveRequest {
  return { userId: 0, color: "", pieceId: "", originX: 0, originY: 0, rotation: 0, flip: false };
}

export const MoveRequest: MessageFns<MoveRequest> = {
  encode(message: MoveRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    if (message.color !== "") {
      writer.uint32(18).string(message.color);
    }
    if (message.pieceId !== "") {
      writer.uint32(26).string(message.pieceId);
    }
    if (message.originX !== 0) {
      writer.uint32(32).int32(message.originX);
    }
    if (message.originY !== 0) {
      writer.uint32(40).int32(message.originY);
    }
    if (message.rotation !== 0) {
      writer.uint32(48).int32(message.rotation);
    }
    if (message.flip !== false) {
      writer.uint32(56).bool(message.flip);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MoveRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMoveRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.userId = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.color = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.pieceId = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 32) {
              break;
            }

            message.originX = reader.int32();
            continue;
          }
          case 5: {
            if (tag !== 40) {
              break;
            }

            message.originY = reader.int32();
            continue;
          }
          case 6: {
            if (tag !== 48) {
              break;
            }

            message.rotation = reader.int32();
            continue;
          }
          case 7: {
            if (tag !== 56) {
              break;
            }

            message.flip = reader.bool();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MoveRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      color: isSet(object.color) ? globalThis.String(object.color) : "",
      pieceId: isSet(object.pieceId)
        ? globalThis.String(object.pieceId)
        : isSet(object.piece_id)
        ? globalThis.String(object.piece_id)
        : "",
      originX: isSet(object.originX)
        ? globalThis.Number(object.originX)
        : isSet(object.origin_x)
        ? globalThis.Number(object.origin_x)
        : 0,
      originY: isSet(object.originY)
        ? globalThis.Number(object.originY)
        : isSet(object.origin_y)
        ? globalThis.Number(object.origin_y)
        : 0,
      rotation: isSet(object.rotation) ? globalThis.Number(object.rotation) : 0,
      flip: isSet(object.flip) ? globalThis.Boolean(object.flip) : false,
    };
  },

  toJSON(message: MoveRequest): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.color !== "") {
      obj.color = message.color;
    }
    if (message.pieceId !== "") {
      obj.pieceId = message.pieceId;
    }
    if (message.originX !== 0) {
      obj.originX = Math.round(message.originX);
    }
    if (message.originY !== 0) {
      obj.originY = Math.round(message.originY);
    }
    if (message.rotation !== 0) {
      obj.rotation = Math.round(message.rotation);
    }
    if (message.flip !== false) {
      obj.flip = message.flip;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MoveRequest>, I>>(base?: I): MoveRequest {
    return MoveRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MoveRequest>, I>>(object: I): MoveRequest {
    const message = createBaseMoveRequest();
    message.userId = object.userId ?? 0;
    message.color = object.color ?? "";
    message.pieceId = object.pieceId ?? "";
    message.originX = object.originX ?? 0;
    message.originY = object.originY ?? 0;
    message.rotation = object.rotation ?? 0;
    message.flip = object.flip ?? false;
    return message;
  },
};

function createBaseGameStateResponse(): GameStateResponse {
  return { isValid: false, errorMessage: "", currentTurnUserId: 0, state: "" };
}

export const GameStateResponse: MessageFns<GameStateResponse> = {
  encode(message: GameStateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isValid !== false) {
      writer.uint32(8).bool(message.isValid);
    }
    if (message.errorMessage !== "") {
      writer.uint32(18).string(message.errorMessage);
    }
    if (message.currentTurnUserId !== 0) {
      writer.uint32(24).int32(message.currentTurnUserId);
    }
    if (message.state !== "") {
      writer.uint32(34).string(message.state);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GameStateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGameStateResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.isValid = reader.bool();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errorMessage = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 24) {
              break;
            }

            message.currentTurnUserId = reader.int32();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.state = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): GameStateResponse {
    return {
      isValid: isSet(object.isValid)
        ? globalThis.Boolean(object.isValid)
        : isSet(object.is_valid)
        ? globalThis.Boolean(object.is_valid)
        : false,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
      currentTurnUserId: isSet(object.currentTurnUserId)
        ? globalThis.Number(object.currentTurnUserId)
        : isSet(object.current_turn_user_id)
        ? globalThis.Number(object.current_turn_user_id)
        : 0,
      state: isSet(object.state) ? globalThis.String(object.state) : "",
    };
  },

  toJSON(message: GameStateResponse): unknown {
    const obj: any = {};
    if (message.isValid !== false) {
      obj.isValid = message.isValid;
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    if (message.currentTurnUserId !== 0) {
      obj.currentTurnUserId = Math.round(message.currentTurnUserId);
    }
    if (message.state !== "") {
      obj.state = message.state;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GameStateResponse>, I>>(base?: I): GameStateResponse {
    return GameStateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GameStateResponse>, I>>(object: I): GameStateResponse {
    const message = createBaseGameStateResponse();
    message.isValid = object.isValid ?? false;
    message.errorMessage = object.errorMessage ?? "";
    message.currentTurnUserId = object.currentTurnUserId ?? 0;
    message.state = object.state ?? "";
    return message;
  },
};

function createBaseGameActionRequest(): GameActionRequest {
  return { userId: 0, action: "", payload: "" };
}

export const GameActionRequest: MessageFns<GameActionRequest> = {
  encode(message: GameActionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    if (message.action !== "") {
      writer.uint32(18).string(message.action);
    }
    if (message.payload !== "") {
      writer.uint32(26).string(message.payload);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GameActionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGameActionRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.userId = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.action = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.payload = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): GameActionRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      action: isSet(object.action) ? globalThis.String(object.action) : "",
      payload: isSet(object.payload) ? globalThis.String(object.payload) : "",
    };
  },

  toJSON(message: GameActionRequest): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.action !== "") {
      obj.action = message.action;
    }
    if (message.payload !== "") {
      obj.payload = message.payload;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GameActionRequest>, I>>(base?: I): GameActionRequest {
    return GameActionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GameActionRequest>, I>>(object: I): GameActionRequest {
    const message = createBaseGameActionRequest();
    message.userId = object.userId ?? 0;
    message.action = object.action ?? "";
    message.payload = object.payload ?? "";
    return message;
  },
};

function createBaseGameStateRequest(): GameStateRequest {
  return { userId: 0 };
}

export const GameStateRequest: MessageFns<GameStateRequest> = {
  encode(message: GameStateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GameStateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseGameStateRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.userId = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): GameStateRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
    };
  },

  toJSON(message: GameStateRequest): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GameStateRequest>, I>>(base?: I): GameStateRequest {
    return GameStateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GameStateRequest>, I>>(object: I): GameStateRequest {
    const message = createBaseGameStateRequest();
    message.userId = object.userId ?? 0;
    return message;
  },
};

function createBaseActionResponse(): ActionResponse {
  return { success: false, errorCode: "", message: "", state: "" };
}

export const ActionResponse: MessageFns<ActionResponse> = {
  encode(message: ActionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.errorCode !== "") {
      writer.uint32(18).string(message.errorCode);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    if (message.state !== "") {
      writer.uint32(34).string(message.state);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseActionResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.success = reader.bool();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.errorCode = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.message = reader.string();
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.state = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): ActionResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      errorCode: isSet(object.errorCode)
        ? globalThis.String(object.errorCode)
        : isSet(object.error_code)
        ? globalThis.String(object.error_code)
        : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      state: isSet(object.state) ? globalThis.String(object.state) : "",
    };
  },

  toJSON(message: ActionResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.errorCode !== "") {
      obj.errorCode = message.errorCode;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.state !== "") {
      obj.state = message.state;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActionResponse>, I>>(base?: I): ActionResponse {
    return ActionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActionResponse>, I>>(object: I): ActionResponse {
    const message = createBaseActionResponse();
    message.success = object.success ?? false;
    message.errorCode = object.errorCode ?? "";
    message.message = object.message ?? "";
    message.state = object.state ?? "";
    return message;
  },
};

function createBaseCreateLobbyPayload(): CreateLobbyPayload {
  return { userName: "", maxPlayers: 0 };
}

export const CreateLobbyPayload: MessageFns<CreateLobbyPayload> = {
  encode(message: CreateLobbyPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userName !== "") {
      writer.uint32(10).string(message.userName);
    }
    if (message.maxPlayers !== 0) {
      writer.uint32(16).int32(message.maxPlayers);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateLobbyPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseCreateLobbyPayload();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.userName = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 16) {
              break;
            }

            message.maxPlayers = reader.int32();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): CreateLobbyPayload {
    return {
      userName: isSet(object.userName)
        ? globalThis.String(object.userName)
        : isSet(object.user_name)
        ? globalThis.String(object.user_name)
        : "",
      maxPlayers: isSet(object.maxPlayers)
        ? globalThis.Number(object.maxPlayers)
        : isSet(object.max_players)
        ? globalThis.Number(object.max_players)
        : 0,
    };
  },

  toJSON(message: CreateLobbyPayload): unknown {
    const obj: any = {};
    if (message.userName !== "") {
      obj.userName = message.userName;
    }
    if (message.maxPlayers !== 0) {
      obj.maxPlayers = Math.round(message.maxPlayers);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateLobbyPayload>, I>>(base?: I): CreateLobbyPayload {
    return CreateLobbyPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateLobbyPayload>, I>>(object: I): CreateLobbyPayload {
    const message = createBaseCreateLobbyPayload();
    message.userName = object.userName ?? "";
    message.maxPlayers = object.maxPlayers ?? 0;
    return message;
  },
};

function createBaseJoinLobbyPayload(): JoinLobbyPayload {
  return { userName: "", lobbyId: "" };
}

export const JoinLobbyPayload: MessageFns<JoinLobbyPayload> = {
  encode(message: JoinLobbyPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userName !== "") {
      writer.uint32(10).string(message.userName);
    }
    if (message.lobbyId !== "") {
      writer.uint32(18).string(message.lobbyId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): JoinLobbyPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseJoinLobbyPayload();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.userName = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.lobbyId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): JoinLobbyPayload {
    return {
      userName: isSet(object.userName)
        ? globalThis.String(object.userName)
        : isSet(object.user_name)
        ? globalThis.String(object.user_name)
        : "",
      lobbyId: isSet(object.lobbyId)
        ? globalThis.String(object.lobbyId)
        : isSet(object.lobby_id)
        ? globalThis.String(object.lobby_id)
        : "",
    };
  },

  toJSON(message: JoinLobbyPayload): unknown {
    const obj: any = {};
    if (message.userName !== "") {
      obj.userName = message.userName;
    }
    if (message.lobbyId !== "") {
      obj.lobbyId = message.lobbyId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<JoinLobbyPayload>, I>>(base?: I): JoinLobbyPayload {
    return JoinLobbyPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<JoinLobbyPayload>, I>>(object: I): JoinLobbyPayload {
    const message = createBaseJoinLobbyPayload();
    message.userName = object.userName ?? "";
    message.lobbyId = object.lobbyId ?? "";
    return message;
  },
};

function createBaseLobbyIdOnlyPayload(): LobbyIdOnlyPayload {
  return { lobbyId: "" };
}

export const LobbyIdOnlyPayload: MessageFns<LobbyIdOnlyPayload> = {
  encode(message: LobbyIdOnlyPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.lobbyId !== "") {
      writer.uint32(10).string(message.lobbyId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LobbyIdOnlyPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLobbyIdOnlyPayload();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.lobbyId = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): LobbyIdOnlyPayload {
    return {
      lobbyId: isSet(object.lobbyId)
        ? globalThis.String(object.lobbyId)
        : isSet(object.lobby_id)
        ? globalThis.String(object.lobby_id)
        : "",
    };
  },

  toJSON(message: LobbyIdOnlyPayload): unknown {
    const obj: any = {};
    if (message.lobbyId !== "") {
      obj.lobbyId = message.lobbyId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LobbyIdOnlyPayload>, I>>(base?: I): LobbyIdOnlyPayload {
    return LobbyIdOnlyPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LobbyIdOnlyPayload>, I>>(object: I): LobbyIdOnlyPayload {
    const message = createBaseLobbyIdOnlyPayload();
    message.lobbyId = object.lobbyId ?? "";
    return message;
  },
};

function createBaseEmptyPayload(): EmptyPayload {
  return {};
}

export const EmptyPayload: MessageFns<EmptyPayload> = {
  encode(_: EmptyPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EmptyPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseEmptyPayload();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): EmptyPayload {
    return {};
  },

  toJSON(_: EmptyPayload): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<EmptyPayload>, I>>(base?: I): EmptyPayload {
    return EmptyPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EmptyPayload>, I>>(_: I): EmptyPayload {
    const message = createBaseEmptyPayload();
    return message;
  },
};

function createBaseLobbyActionRequest(): LobbyActionRequest {
  return { userId: 0, payload: undefined };
}

export const LobbyActionRequest: MessageFns<LobbyActionRequest> = {
  encode(message: LobbyActionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    switch (message.payload?.$case) {
      case "createLobby":
        CreateLobbyPayload.encode(message.payload.createLobby, writer.uint32(18).fork()).join();
        break;
      case "joinLobby":
        JoinLobbyPayload.encode(message.payload.joinLobby, writer.uint32(26).fork()).join();
        break;
      case "toggleReady":
        LobbyIdOnlyPayload.encode(message.payload.toggleReady, writer.uint32(34).fork()).join();
        break;
      case "leaveLobby":
        EmptyPayload.encode(message.payload.leaveLobby, writer.uint32(42).fork()).join();
        break;
      case "beginReadyCheck":
        LobbyIdOnlyPayload.encode(message.payload.beginReadyCheck, writer.uint32(50).fork()).join();
        break;
      case "acceptReadyCheck":
        LobbyIdOnlyPayload.encode(message.payload.acceptReadyCheck, writer.uint32(58).fork()).join();
        break;
      case "declineReadyCheck":
        LobbyIdOnlyPayload.encode(message.payload.declineReadyCheck, writer.uint32(66).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LobbyActionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseLobbyActionRequest();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.userId = reader.int32();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.payload = { $case: "createLobby", createLobby: CreateLobbyPayload.decode(reader, reader.uint32()) };
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.payload = { $case: "joinLobby", joinLobby: JoinLobbyPayload.decode(reader, reader.uint32()) };
            continue;
          }
          case 4: {
            if (tag !== 34) {
              break;
            }

            message.payload = { $case: "toggleReady", toggleReady: LobbyIdOnlyPayload.decode(reader, reader.uint32()) };
            continue;
          }
          case 5: {
            if (tag !== 42) {
              break;
            }

            message.payload = { $case: "leaveLobby", leaveLobby: EmptyPayload.decode(reader, reader.uint32()) };
            continue;
          }
          case 6: {
            if (tag !== 50) {
              break;
            }

            message.payload = {
              $case: "beginReadyCheck",
              beginReadyCheck: LobbyIdOnlyPayload.decode(reader, reader.uint32()),
            };
            continue;
          }
          case 7: {
            if (tag !== 58) {
              break;
            }

            message.payload = {
              $case: "acceptReadyCheck",
              acceptReadyCheck: LobbyIdOnlyPayload.decode(reader, reader.uint32()),
            };
            continue;
          }
          case 8: {
            if (tag !== 66) {
              break;
            }

            message.payload = {
              $case: "declineReadyCheck",
              declineReadyCheck: LobbyIdOnlyPayload.decode(reader, reader.uint32()),
            };
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): LobbyActionRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.Number(object.userId)
        : isSet(object.user_id)
        ? globalThis.Number(object.user_id)
        : 0,
      payload: isSet(object.createLobby)
        ? { $case: "createLobby", createLobby: CreateLobbyPayload.fromJSON(object.createLobby) }
        : isSet(object.create_lobby)
        ? { $case: "createLobby", createLobby: CreateLobbyPayload.fromJSON(object.create_lobby) }
        : isSet(object.joinLobby)
        ? { $case: "joinLobby", joinLobby: JoinLobbyPayload.fromJSON(object.joinLobby) }
        : isSet(object.join_lobby)
        ? { $case: "joinLobby", joinLobby: JoinLobbyPayload.fromJSON(object.join_lobby) }
        : isSet(object.toggleReady)
        ? { $case: "toggleReady", toggleReady: LobbyIdOnlyPayload.fromJSON(object.toggleReady) }
        : isSet(object.toggle_ready)
        ? { $case: "toggleReady", toggleReady: LobbyIdOnlyPayload.fromJSON(object.toggle_ready) }
        : isSet(object.leaveLobby)
        ? { $case: "leaveLobby", leaveLobby: EmptyPayload.fromJSON(object.leaveLobby) }
        : isSet(object.leave_lobby)
        ? { $case: "leaveLobby", leaveLobby: EmptyPayload.fromJSON(object.leave_lobby) }
        : isSet(object.beginReadyCheck)
        ? { $case: "beginReadyCheck", beginReadyCheck: LobbyIdOnlyPayload.fromJSON(object.beginReadyCheck) }
        : isSet(object.begin_ready_check)
        ? { $case: "beginReadyCheck", beginReadyCheck: LobbyIdOnlyPayload.fromJSON(object.begin_ready_check) }
        : isSet(object.acceptReadyCheck)
        ? { $case: "acceptReadyCheck", acceptReadyCheck: LobbyIdOnlyPayload.fromJSON(object.acceptReadyCheck) }
        : isSet(object.accept_ready_check)
        ? { $case: "acceptReadyCheck", acceptReadyCheck: LobbyIdOnlyPayload.fromJSON(object.accept_ready_check) }
        : isSet(object.declineReadyCheck)
        ? { $case: "declineReadyCheck", declineReadyCheck: LobbyIdOnlyPayload.fromJSON(object.declineReadyCheck) }
        : isSet(object.decline_ready_check)
        ? { $case: "declineReadyCheck", declineReadyCheck: LobbyIdOnlyPayload.fromJSON(object.decline_ready_check) }
        : undefined,
    };
  },

  toJSON(message: LobbyActionRequest): unknown {
    const obj: any = {};
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.payload?.$case === "createLobby") {
      obj.createLobby = CreateLobbyPayload.toJSON(message.payload.createLobby);
    } else if (message.payload?.$case === "joinLobby") {
      obj.joinLobby = JoinLobbyPayload.toJSON(message.payload.joinLobby);
    } else if (message.payload?.$case === "toggleReady") {
      obj.toggleReady = LobbyIdOnlyPayload.toJSON(message.payload.toggleReady);
    } else if (message.payload?.$case === "leaveLobby") {
      obj.leaveLobby = EmptyPayload.toJSON(message.payload.leaveLobby);
    } else if (message.payload?.$case === "beginReadyCheck") {
      obj.beginReadyCheck = LobbyIdOnlyPayload.toJSON(message.payload.beginReadyCheck);
    } else if (message.payload?.$case === "acceptReadyCheck") {
      obj.acceptReadyCheck = LobbyIdOnlyPayload.toJSON(message.payload.acceptReadyCheck);
    } else if (message.payload?.$case === "declineReadyCheck") {
      obj.declineReadyCheck = LobbyIdOnlyPayload.toJSON(message.payload.declineReadyCheck);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LobbyActionRequest>, I>>(base?: I): LobbyActionRequest {
    return LobbyActionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LobbyActionRequest>, I>>(object: I): LobbyActionRequest {
    const message = createBaseLobbyActionRequest();
    message.userId = object.userId ?? 0;
    switch (object.payload?.$case) {
      case "createLobby": {
        if (object.payload?.createLobby !== undefined && object.payload?.createLobby !== null) {
          message.payload = {
            $case: "createLobby",
            createLobby: CreateLobbyPayload.fromPartial(object.payload.createLobby),
          };
        }
        break;
      }
      case "joinLobby": {
        if (object.payload?.joinLobby !== undefined && object.payload?.joinLobby !== null) {
          message.payload = { $case: "joinLobby", joinLobby: JoinLobbyPayload.fromPartial(object.payload.joinLobby) };
        }
        break;
      }
      case "toggleReady": {
        if (object.payload?.toggleReady !== undefined && object.payload?.toggleReady !== null) {
          message.payload = {
            $case: "toggleReady",
            toggleReady: LobbyIdOnlyPayload.fromPartial(object.payload.toggleReady),
          };
        }
        break;
      }
      case "leaveLobby": {
        if (object.payload?.leaveLobby !== undefined && object.payload?.leaveLobby !== null) {
          message.payload = { $case: "leaveLobby", leaveLobby: EmptyPayload.fromPartial(object.payload.leaveLobby) };
        }
        break;
      }
      case "beginReadyCheck": {
        if (object.payload?.beginReadyCheck !== undefined && object.payload?.beginReadyCheck !== null) {
          message.payload = {
            $case: "beginReadyCheck",
            beginReadyCheck: LobbyIdOnlyPayload.fromPartial(object.payload.beginReadyCheck),
          };
        }
        break;
      }
      case "acceptReadyCheck": {
        if (object.payload?.acceptReadyCheck !== undefined && object.payload?.acceptReadyCheck !== null) {
          message.payload = {
            $case: "acceptReadyCheck",
            acceptReadyCheck: LobbyIdOnlyPayload.fromPartial(object.payload.acceptReadyCheck),
          };
        }
        break;
      }
      case "declineReadyCheck": {
        if (object.payload?.declineReadyCheck !== undefined && object.payload?.declineReadyCheck !== null) {
          message.payload = {
            $case: "declineReadyCheck",
            declineReadyCheck: LobbyIdOnlyPayload.fromPartial(object.payload.declineReadyCheck),
          };
        }
        break;
      }
    }
    return message;
  },
};

export interface GameEngine {
  ValidateAndMakeMove(request: MoveRequest): Promise<GameStateResponse>;
  /**
   * Lobby action: CREATE_LOBBY, JOIN_LOBBY, TOGGLE_READY, LEAVE_LOBBY,
   * BEGIN_READY_CHECK, ACCEPT_READY_CHECK, DECLINE_READY_CHECK.
   */
  HandleLobbyAction(request: LobbyActionRequest): Promise<ActionResponse>;
  /** Game action: MAKE_MOVE, PASS_TURN, DISCONNECT. */
  HandleGameAction(request: GameActionRequest): Promise<ActionResponse>;
  GetGameStateSnapshot(request: GameStateRequest): Promise<ActionResponse>;
}

export const GameEngineServiceName = "game.GameEngine";
export class GameEngineClientImpl implements GameEngine {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || GameEngineServiceName;
    this.rpc = rpc;
    this.ValidateAndMakeMove = this.ValidateAndMakeMove.bind(this);
    this.HandleLobbyAction = this.HandleLobbyAction.bind(this);
    this.HandleGameAction = this.HandleGameAction.bind(this);
    this.GetGameStateSnapshot = this.GetGameStateSnapshot.bind(this);
  }
  ValidateAndMakeMove(request: MoveRequest): Promise<GameStateResponse> {
    const data = MoveRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ValidateAndMakeMove", data);
    return promise.then((data) => GameStateResponse.decode(new BinaryReader(data)));
  }

  HandleLobbyAction(request: LobbyActionRequest): Promise<ActionResponse> {
    const data = LobbyActionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "HandleLobbyAction", data);
    return promise.then((data) => ActionResponse.decode(new BinaryReader(data)));
  }

  HandleGameAction(request: GameActionRequest): Promise<ActionResponse> {
    const data = GameActionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "HandleGameAction", data);
    return promise.then((data) => ActionResponse.decode(new BinaryReader(data)));
  }

  GetGameStateSnapshot(request: GameStateRequest): Promise<ActionResponse> {
    const data = GameStateRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetGameStateSnapshot", data);
    return promise.then((data) => ActionResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
